### ISSUE TITLE
[Bug] writing a reply to s toote and sliding down it, makes impossible to recover to continuing with the text 

### ISSUE THREAD

**Issue by ferlanero** [dysk0/harbour-tooter#10]
When you are writing a replay, if you  slide down it that  replay to  see the tootes above, it  makes impossible to recover the text you  were writing before

**Comment by ferlanero** [comment]
![captura_20170620_004](https://user-images.githubusercontent.com/1192395/27348586-e12c3cfa-55f4-11e7-8e4c-c0c8fe428115.png)
![captura_20170620_005](https://user-images.githubusercontent.com/1192395/27348584-e125c8fc-55f4-11e7-869d-983d57cf816c.png)
![captura_20170620_007](https://user-images.githubusercontent.com/1192395/27348676-2ccf8d38-55f5-11e7-843d-4ee26530b2db.png)

**Comment by dysk0** [comment]
Tnx for the report. Fixed!
