### ISSUE TITLE
unable to connect to unixcorn.xyz

### ISSUE THREAD

**Issue by ghost** [dysk0/harbour-tooter#12]
Hi, 

I'm unable to authorize Tooter.
Clicking on Accept does nothing on my JollaC.
![capture d ecran_20170626_001](https://user-images.githubusercontent.com/13441278/27550165-f63964b6-5a9e-11e7-86b4-a29c77b6fa21.png)

**Comment by dysk0** [comment]
Fixed... Will be live with next update.
