### ISSUE TITLE
tooter not load in home

### ISSUE THREAD

**Issue by ghost** [dysk0/harbour-tooter#22]
Hello dysk0
I just want to report that tooter in my case never load in Home only show the icon that loading but never done. this issue being for long time ago.

thank in advance.

**Comment by dysk0** [comment]
Hi there. It is strange. On which instance you are?

**Comment by ghost** [comment]
In mastodon.social

**Comment by dysk0** [comment]
I am there too, and it works for me :) strange :)

**Comment by ghost** [comment]
ok. i will reinstall the app. i will close this issue. tnks.

**Comment by ghost** [comment]
This issue still persists in  my jolla c, and my new sony xperia X too.

**Comment by dysk0** [comment]
it is strange because my account is on mastodon.social and I have no issues. if you can - connect it to the computer and send me console.logs

**Comment by ghost** [comment]
[D] unknown:0 - Using Wayland-EGL
[W] unknown:0 - Defaulting to webview scaling factor of 1.0
[D] :32 - db.version: 0.1
[D] :47 - READING CONF FROM DB
[D] :50 - id 	 > 	 "121695"
[D] :50 - name 	 > 	 "Tooter"
[D] :50 - website 	 > 	 "http://grave-design.com/harbour-tooter"
[D] :50 - redirect_uri 	 > 	 "http://localhost/harbour-tooter"
[D] :50 - client_id 	 > 	 "201fd3a2202fdb4b8de2a725b0de833dd1f9b36471916e7582608ec1a1e4ceb4"
[D] :50 - client_secret 	 > 	 "5f05222de12cbcb6ee38d443169ff92717211606681d03e9aad3c5610a653d5b"
[D] :50 - instance 	 > 	 "https://mastodon.social"
[D] :50 - login 	 > 	 true
[D] :50 - notificationLastID 	 > 	 "3088187"
[D] :50 - api_user_token 	 > 	 "700571fb52b505730f1fb2555dcf883d1dd0c408fd6ff80bd3f7210c58852226"
[D] :50 - loadImages 	 > 	 true
[D] :53 - END OF READING
[D] :54 - {"id":"121695","name":"Tooter","website":"http://grave-design.com/harbour-tooter","redirect_uri":"http://localhost/harbour-tooter","client_id":"201fd3a2202fdb4b8de2a725b0de833dd1f9b36471916e7582608ec1a1e4ceb4","client_secret":"5f05222de12cbcb6ee38d443169ff92717211606681d03e9aad3c5610a653d5b","instance":"https://mastodon.social","login":true,"notificationLastID":"3088187","api_user_token":"700571fb52b505730f1fb2555dcf883d1dd0c408fd6ff80bd3f7210c58852226","loadImages":true}
[D] :46 - confLoaded
[D] :47 - {"id":"121695","name":"Tooter","website":"http://grave-design.com/harbour-tooter","redirect_uri":"http://localhost/harbour-tooter","client_id":"201fd3a2202fdb4b8de2a725b0de833dd1f9b36471916e7582608ec1a1e4ceb4","client_secret":"5f05222de12cbcb6ee38d443169ff92717211606681d03e9aad3c5610a653d5b","instance":"https://mastodon.social","login":true,"notificationLastID":"3088187","api_user_token":"700571fb52b505730f1fb2555dcf883d1dd0c408fd6ff80bd3f7210c58852226","loadImages":true}
[D] :50 - ?
[D] :61 - Successful GET API request to https://mastodon.social/api/v1/instance
[D] :58 - {"uri":"mastodon.social","title":"Mastodon","description":"This page describes the mastodon.social <em>instance</em> - wondering what Mastodon is? Check out <a href=\"https://joinmastodon.org\">joinmastodon.org</a> instead! In essence, Mastodon is a decentralized, open source social network. This is just one part of the network, run by the main developers of the project <img draggable=\"false\" alt=\"?\" class=\"emojione\" src=\"https://mastodon.social/emoji/1f418.svg\" /> It is not focused on any particular niche interest - everyone is welcome as long as you follow our code of conduct!","email":"eugen@zeonfederated.com","version":"2.0.0","urls":{"streaming_api":"wss://mastodon.social"},"stats":{"user_count":116969,"status_count":3894772,"domain_count":3450},"thumbnail":"https://files.mastodon.social/site_uploads/files/000/000/001/original/DN5wMUeVQAENPwp.jpg_large.jpeg"}
[W] unknown:87 - file:///usr/share/harbour-tooter/qml/pages/MainPage.qml:87: TypeError: Cannot read property 'itemHeight' of null
[W] unknown:86 - file:///usr/share/harbour-tooter/qml/pages/MainPage.qml:86: TypeError: Cannot read property 'itemWidth' of null
[D] checkNotifications:121 - checkNotifications
[D] onStatusChanged:45 - PageStatus.Inactive
[D] :4 - Action > notifications
[D] :5 - Model > QQmlListModelWorkerAgent(0xab6c7498)
[D] :6 - Mode > prepend
[D] :7 - Conf > {"id":"121695","name":"Tooter","website":"http://grave-design.com/harbour-tooter","redirect_uri":"http://localhost/harbour-tooter","client_id":"201fd3a2202fdb4b8de2a725b0de833dd1f9b36471916e7582608ec1a1e4ceb4","client_secret":"5f05222de12cbcb6ee38d443169ff92717211606681d03e9aad3c5610a653d5b","instance":"https://mastodon.social","login":true,"notificationLastID":"3088187","api_user_token":"700571fb52b505730f1fb2555dcf883d1dd0c408fd6ff80bd3f7210c58852226","loadImages":true}
[D] :8 - Params > []
[D] :50 - ?
[D] :4 - Action > timelines/public
[D] :5 - Model > QQmlListModelWorkerAgent(0xab6e3a48)
[D] :6 - Mode > prepend
[D] :7 - Conf > {"id":"121695","name":"Tooter","website":"http://grave-design.com/harbour-tooter","redirect_uri":"http://localhost/harbour-tooter","client_id":"201fd3a2202fdb4b8de2a725b0de833dd1f9b36471916e7582608ec1a1e4ceb4","client_secret":"5f05222de12cbcb6ee38d443169ff92717211606681d03e9aad3c5610a653d5b","instance":"https://mastodon.social","login":true,"notificationLastID":"3088187","api_user_token":"700571fb52b505730f1fb2555dcf883d1dd0c408fd6ff80bd3f7210c58852226","loadImages":true}
[D] :8 - Params > []
[D] :50 - ?
[D] :4 - Action > timelines/home
[D] :5 - Model > QQmlListModelWorkerAgent(0xab605ff0)
[D] :6 - Mode > prepend
[D] :7 - Conf > {"id":"121695","name":"Tooter","website":"http://grave-design.com/harbour-tooter","redirect_uri":"http://localhost/harbour-tooter","client_id":"201fd3a2202fdb4b8de2a725b0de833dd1f9b36471916e7582608ec1a1e4ceb4","client_secret":"5f05222de12cbcb6ee38d443169ff92717211606681d03e9aad3c5610a653d5b","instance":"https://mastodon.social","login":true,"notificationLastID":"3088187","api_user_token":"700571fb52b505730f1fb2555dcf883d1dd0c408fd6ff80bd3f7210c58852226","loadImages":true}
[D] :8 - Params > []
[D] :50 - ?
[D] :61 - Successful GET API request to https://mastodon.social/api/v1/timelines/public
[D] addDataToModel:115 - Fetched > 20
[D] :61 - Successful GET API request to https://mastodon.social/api/v1/timelines/home
[D] addDataToModel:115 - Fetched > 13
[D] :61 - Successful GET API request to https://mastodon.social/api/v1/notifications
[D] addDataToModel:115 - Fetched > 1
[W] unknown:31 - file:///usr/share/harbour-tooter/qml/pages/components/VisualContainer.qml:31:5: QML Image: Error transferring https://files.mastodon.social/accounts/avatars/000/127/636/original/2ae2d368fb8e8f4b.jpeg - server replied: Forbidden

**Comment by ghost** [comment]
I close this ,because never was an issue. Was a problem on my side. now  everything looks like  working...
