### ISSUE TITLE
More sentences to translate is needed.

### ISSUE THREAD

**Issue by ghost** [dysk0/harbour-tooter#25]
![captura_20171102_001](https://user-images.githubusercontent.com/24536606/32333725-f8cdc598-bfbe-11e7-9375-4ddfc4222e48.png)

**Comment by dysk0** [comment]
Ok, I'll add it. Please note that Transifex will be used as a translation tool.

**Comment by dysk0** [comment]
Added

**Comment by ghost** [comment]
Thank you, can you refresh translationPages 100% to translate? because label-qstr is not incluyed yet.
Thanks

**Comment by dysk0** [comment]
It should be automatically pulled in. I'll check
