### ISSUE TITLE
Possible to break the search page

### ISSUE THREAD

**Issue by Thra11** [dysk0/harbour-tooter#26]
Affects version 0.2.4.
To reproduce:
1. Switch to the search page.
2. Type at least one character into the search field and press the down arrow on the keyboard to start the search.
3. Empty the search field, either with the clear button or using backspace.
4. Press the down arrow. The search page is replaced by a loading circle icon in the top left corner. You have to restart the application to get search working again.

**Comment by dysk0** [comment]
Tnx. I'll take a look.
