### ISSUE TITLE
spanish is not shipped on -v0.2.6

### ISSUE THREAD

**Issue by ghost** [dysk0/harbour-tooter#29]
After install -v0.2.6 spanish is gone,
I am of curious why you rename harbour-tooter to harbour-tooterts maybe that is causing a conflict.

**Comment by dysk0** [comment]
Those names are given by Transifex, and I would like not to rename them every time. It worked fine on my device, but app must be deployed to the device and then closed and opened. From the Store it should work just fine.

**Comment by ghost** [comment]
hello dysk0
i reopen this issue because never was  fixed. even installed from jollla-store.

**Comment by ghost** [comment]
please fix this issue.

**Comment by dysk0** [comment]
Hi... It will be handled soon... Sorry

**Comment by ghost** [comment]
same issue v2.7

**Comment by ghost** [comment]
maybe the issue is -es.xml

**Comment by ghost** [comment]
fixed in v1.0.0

**Comment by dysk0** [comment]
@GNUuser tnx. i was aware of that issue but just needed some time to resolve it.

**Comment by ghost** [comment]
thank you.
