### ISSUE TITLE
Clicking on boosted toot doesn't show conversation

### ISSUE THREAD

**Issue by Thra11** [dysk0/harbour-tooter#33]
If you click (touch) a boosted toot, it shows you the boost, not the original toot. This means you don't see any conversation around the original toot (I'm not sure if it's possible for the 'boost' to be part of its own conversation, separate from the toot it boosted, but I've never seen it, so I assume not).

Currently, it seems to only way to see the conversation around the original toot is to click the avatar to get the original toot's author, then scroll through until you see the toot that was boosted, at which point clicking on it shows the conversation.

**Comment by dysk0** [comment]
I believe that this will be fixed soon, I must few tests to run :)
