### ISSUE TITLE
Boosted toots lose content warnings

### ISSUE THREAD

**Issue by Thra11** [dysk0/harbour-tooter#34]
If a toot has a content warning, it is hidden until the user decides to reveal it. However, if a toot with a content warning is shown in the timeline because someone boosted it, it is immediately visible, as though it had no content warning.

**Comment by dysk0** [comment]
Tnx I'll check

**Comment by dysk0** [comment]
I believe it is fixed, please update an confirm.

**Comment by Thra11** [comment]
Yes, confirmed fixed. Thanks!
